import AboutPageComponent from '@/components/AboutPageComponent'
import React from 'react'


import { Metadata } from 'next'


export const metadata: Metadata = {
  title: "About Us | Tecklo",
  description: "Generated by create next app",
};




function page() {
  return (
    <div>
      <AboutPageComponent/>
    </div>
  )
}

export default page