import ServiceComponent from '@/components/ServiceComponent'
import React from 'react'

import { Metadata } from 'next'


export const metadata: Metadata = {
  title: "Services we provide",
  description: "Generated by create next app",
};




function page() {
  return (
    <div>
      <ServiceComponent/>
    </div>
  )
}

export default page